version: '3.8'

services:
  db:
    image: mariadb:lts
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: flaskdb
      MARIADB_USER: flaskuser
      MARIADB_PASSWORD: flaskpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mariadb
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: '5s'
      timeout: '5s'
      retries: 5


  web:
    build: .
    container_name: pythondocker-container
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    environment:
      FLASK_ENV: development
      DATABASE_URL: mysql+pymysql://flaskuser:flaskpassword@db/flaskdb

volumes:
  db_data: