---
- hosts: all
  become: yes
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Setup Nginx configuration
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/pythonWeb

    - name: Enable Nginx configuration
      file:
        src: /etc/nginx/sites-available/pythonWeb
        dest: /etc/nginx/sites-enabled/pythonWeb
        state: link

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
  