---
- hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install necessary packages
      apt:
        name:
          - python3
          - python3-pip
          - git

    - name: Get uname -s
      shell: uname -s
      register: uname_s
      changed_when: false

    - name: Get uname -m
      shell: uname -m
      register: uname_m
      changed_when: false

    - name: Install Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ uname_s.stdout }}-{{ uname_m.stdout }}"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Clone the project repository
      git:
        repo: 'https://github.com/Phenixel/pythonWeb.git'
        dest: /home/phen/pythonWeb

    - name: Create a virtual environment
      command: python3 -m venv venv
      args:
        chdir: '/home/phen/pythonWeb'

    - name: Install project dependencies
      pip:
        requirements: /home/phen/pythonWeb/requirements.txt
        virtualenv: '/home/phen/pythonWeb/venv'

    - name: Build and start Docker services
      command: docker-compose up -d
      args:
        chdir: /home/phen/pythonWeb
