name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible
          ansible --version

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/cloudixel
          chmod 400 ~/.ssh/cloudixel
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Verify SSH Key Exists
        run: |
          if [ ! -f ~/.ssh/cloudixel ]; then
            echo "SSH key does not exist"
            exit 1
          fi

      - name: Debug SSH Connection
        run: |
          ssh -vvv -i ~/.ssh/cloudixel cloudixel@${{ secrets.SERVER_HOST }} exit

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i ./ansible/inventory ./ansible/launch.yml --private-key ~/.ssh/cloudixel