name: Test and Create PR

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test docker-compose
        run: |
          docker-compose -f docker-compose.yml config -q

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Apply changes"
          title: "Automated PR to Main"
          body: "This is an automated pull request to update the container image"
          branch: "feature-branch-name"
          base: "main"
